### PR TITLE
Feature/tests

### PR DESCRIPTION
**Pull request by ctot-nondef**
some basic tests

### CODE REVIEW

**Comment by waltster** [comment]
Hi,

These all look good! The only thing I see is that the LICENSE should be updated to the Apache2 license. You could also untrack this file if you'd like. 

Thanks!

**Comment by ctot-nondef** [comment]
Thanks for the quick reply, I merged your updates to master into my branch, so the license in this branch should match the one you added, no? maybe I missed something?

**Review by waltster — APPROVED** [review]
This is all great! Thank you for this.

**Comment by waltster** [comment]
Okay, apologies, I took another look and I was mistaken.

**Pull request merged**
